-- ==========================================================
-- PROJETO: GESTÃO DE MANUTENÇÃO DE FROTA
-- OBJETIVO: Controle de odômetro, custos e alertas preventivos
-- BANCO: Oracle Database
-- ==========================================================
--Table--
CREATE TABLE TB_FROTA_VEICULOS (
    ID_VEICULO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PLACA VARCHAR2(10) NOT NULL UNIQUE,
    MODELO VARCHAR2(50),
    KM_ATUAL NUMBER DEFAULT 0,
    STATUS VARCHAR2(20) DEFAULT 'ATIVO' -- ATIVO, MANUTENCAO, VENDIDO
);

-- Tabela de Planos (Regras)
CREATE TABLE TB_FROTA_PLANOS (
    ID_PLANO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DESCRICAO VARCHAR2(100),
    INTERVALO_KM NUMBER NOT NULL -- Ex: 10000 para trocar a cada 10 mil km
);

-- Registro de Manutenções
CREATE TABLE TB_FROTA_MANUTENCAO (
    ID_MANUTENCAO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_VEICULO NUMBER REFERENCES TB_FROTA_VEICULOS(ID_VEICULO),
    DATA_SERVICO DATE DEFAULT SYSDATE,
    KM_ODOMETRO NUMBER,
    VALOR_TOTAL NUMBER(10,2),
    OBSERVACOES CLOB
);

--Tabela de Alertas
CREATE TABLE TB_FROTA_ALERTAS (
    ID_ALERTA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_VEICULO NUMBER REFERENCES TB_FROTA_VEICULOS(ID_VEICULO),
    MENSAGEM VARCHAR2(200),
    DATA_GERACAO DATE DEFAULT SYSDATE,
    STATUS_ALERTA VARCHAR2(20) DEFAULT 'PENDENTE' -- PENDENTE, RESOLVIDO
);


--Procedure--
CREATE OR REPLACE PROCEDURE PRC_REGISTRAR_MANUTENCAO (
    p_id_veiculo   IN TB_FROTA_VEICULOS.ID_VEICULO%TYPE,
    p_km_servico   IN NUMBER,
    p_valor        IN NUMBER,
    p_obs          IN VARCHAR2
) AS
    v_km_atual TB_FROTA_VEICULOS.KM_ATUAL%TYPE;
BEGIN
    -- 1.Validação básica: Não permitir manutenção com KM inferior à atual
    SELECT KM_ATUAL INTO v_km_atual 
    FROM TB_FROTA_VEICULOS 
    WHERE ID_VEICULO = p_id_veiculo;

    IF p_km_servico < v_km_atual THEN
        RAISE_APPLICATION_ERROR(-20001, 'A KM da manutenção não pode ser menor que a KM atual do veículo.');
    END IF;

    -- 2.Inserir o registro de manutenção
    INSERT INTO TB_FROTA_MANUTENCAO (
        ID_VEICULO, 
        KM_ODOMETRO, 
        VALOR_TOTAL, 
        OBSERVACOES
    ) VALUES (
        p_id_veiculo, 
        p_km_servico, 
        p_valor, 
        p_obs
    );

    -- 3.Atualizar a KM no cadastro do veículo
    UPDATE TB_FROTA_VEICULOS 
    SET KM_ATUAL = p_km_servico
    WHERE ID_VEICULO = p_id_veiculo;

    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Manutenção registrada e odômetro atualizado com sucesso!');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Erro: Veículo não encontrado.');
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Erro inesperado: ' || SQLERRM);
END PRC_REGISTRAR_MANUTENCAO;

--Trigger--
CREATE OR REPLACE TRIGGER TRG_CHECK_MANUTENCAO
AFTER UPDATE OF KM_ATUAL ON TB_FROTA_VEICULOS
FOR EACH ROW
DECLARE
    v_ultima_km_manut NUMBER;
    v_intervalo       NUMBER := 10000; -- Vamos usar o padrão de 10k por enquanto
BEGIN
    -- Busca a KM da última manutenção realizada para este veículo
    BEGIN
        SELECT MAX(KM_ODOMETRO) 
        INTO v_ultima_km_manut
        FROM TB_FROTA_MANUTENCAO
        WHERE ID_VEICULO = :NEW.ID_VEICULO;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN v_ultima_km_manut := 0;
    END;

    -- Se não houver manutenção, v_ultima_km_manut pode vir nulo
    v_ultima_km_manut := NVL(v_ultima_km_manut, 0);

    -- Lógica: Se a KM atual for 10k maior que a última revisão
    IF :NEW.KM_ATUAL >= (v_ultima_km_manut + v_intervalo) THEN
        INSERT INTO TB_FROTA_ALERTAS (ID_VEICULO, MENSAGEM)
        VALUES (:NEW.ID_VEICULO, 
                'ALERTA: Veículo ' || :NEW.PLACA || ' atingiu ' || :NEW.KM_ATUAL || 
                'km. Necessário realizar troca de óleo (Intervalo de ' || v_intervalo || 'km).');
    END IF;
END;

--View--
CREATE OR REPLACE VIEW VW_DASHBOARD_FROTA AS
SELECT 
    V.ID_VEICULO,
    V.PLACA,
    V.MODELO,
    V.KM_ATUAL,
    V.STATUS,
    -- Busca a data da última manutenção
    (SELECT MAX(DATA_SERVICO) FROM TB_FROTA_MANUTENCAO M WHERE M.ID_VEICULO = V.ID_VEICULO) AS DATA_ULTIMA_REVISAO,
    -- Busca a KM da última manutenção
    (SELECT MAX(KM_ODOMETRO) FROM TB_FROTA_MANUTENCAO M WHERE M.ID_VEICULO = V.ID_VEICULO) AS KM_ULTIMA_REVISAO,
    -- Calcula quanto rodou desde a última revisão
    V.KM_ATUAL - NVL((SELECT MAX(KM_ODOMETRO) FROM TB_FROTA_MANUTENCAO M WHERE M.ID_VEICULO = V.ID_VEICULO), V.KM_ATUAL) AS KM_RODADOS_APOS_REVISAO,
    -- Soma o custo total gasto com o veículo
    NVL((SELECT SUM(VALOR_TOTAL) FROM TB_FROTA_MANUTENCAO M WHERE M.ID_VEICULO = V.ID_VEICULO), 0) AS CUSTO_TOTAL_MANUTENCAO,
    -- Define a prioridade de atenção
    CASE 
        WHEN (V.KM_ATUAL - NVL((SELECT MAX(KM_ODOMETRO) FROM TB_FROTA_MANUTENCAO M WHERE M.ID_VEICULO = V.ID_VEICULO), 0)) >= 10000 THEN 'ALTA - REVISAR AGORA'
        WHEN (V.KM_ATUAL - NVL((SELECT MAX(KM_ODOMETRO) FROM TB_FROTA_MANUTENCAO M WHERE M.ID_VEICULO = V.ID_VEICULO), 0)) >= 8000 THEN 'MÉDIA - AGENDAR'
        ELSE 'NORMAL'
    END AS PRIORIDADE_MANUTENCAO
FROM 
    TB_FROTA_VEICULOS V;

    
