CREATE TABLE TB_TEMPORADAS (
    ANO INT PRIMARY KEY,
    STATUS VARCHAR2(100)
);

CREATE TABLE TB_CIRCUITOS (
    ID_CIRCUITO INT PRIMARY KEY,
    NOME VARCHAR2(100),
    LOCAL VARCHAR2(100),
    CARACTERISTICAS VARCHAR2(100)
);

CREATE TABLE TB_CONSTRUTORES(
    ID_CONSTRUTOR INT PRIMARY KEY,
    EQUIPE VARCHAR2(100),
    NACIONALIDADE VARCHAR2(100)
);

CREATE TABLE TB_PILOTOS(
    ID_PILOTO INT PRIMARY KEY,
    NOME VARCHAR2(100),
    EQUIPE VARCHAR2(100),
    SIGLA varCHAR(3),
    DT_NASCIMENTO DATE,
    NACIONALIDADE VARCHAR2(100),
    ID_CONSTRUTOR INT,
    CONSTRAINT FK_PILOTO_EQUIPE FOREIGN KEY (ID_CONSTRUTOR) REFERENCES TB_CONSTRUTORES(ID_CONSTRUTOR)
);

CREATE TABLE TB_RESULTADOS(
    ID_RESULTADO INT PRIMARY KEY,
    ANO INT,
    ID_CIRCUITO INT,
    ID_PILOTO INT,
    POSICAO_LARGADA INT,
    POSICAO_CHEGADA INT,
    PONTOS_GANHOS NUMBER(4,1), -- 4 dígitos totais, 1 decimal 
    VOLTA_MAIS_RAPIDA VARCHAR2(10), -- Formato '01:10.543'
    STATUS_FINAL VARCHAR2(50), -- 'Finished', 'Collision', 'Engine', etc.
    CONSTRAINT FK_RES_PILOTO FOREIGN KEY (ID_PILOTO) REFERENCES TB_PILOTOS(ID_PILOTO),
    CONSTRAINT FK_RES_ANO FOREIGN KEY (ANO) REFERENCES TB_TEMPORADAS(ANO),
    CONSTRAINT FK_RES_CIRCUITO FOREIGN KEY (ID_CIRCUITO) REFERENCES TB_CIRCUITOS(ID_CIRCUITO)
);

CREATE TABLE STG_F1_CARGA (
    STG_NOME_PILOTO      VARCHAR2(200),
    STG_SIGLA_PILOTO     VARCHAR2(10),
    STG_EQUIPE           VARCHAR2(100),
    STG_CIRCUITO         VARCHAR2(100),
    STG_ANO              VARCHAR2(4),
    STG_POS_LARGADA      VARCHAR2(10),
    STG_POS_CHEGADA      VARCHAR2(10),
    STG_PONTOS           VARCHAR2(10),
    STG_VOLTA_RAPIDA     VARCHAR2(20),
    STG_STATUS_FINAL     VARCHAR2(100),
    DT_CARGA             DATE DEFAULT SYSDATE -- Para controle de quando o Python rodou
);

CREATE or REPLACE VIEW INFORMACAO_GERAL AS
 SELECT
    P.NOME,
    P.SIGLA,
    P.NACIONALIDADE NACIONALIDADE_PILOTO,
    P.DT_NASCIMENTO,
    P.EQUIPE,
    E.NACIONALIDADE NACIONALIDADE_EQUIPE,
    T.ANO,
    T.STATUS,
    C.NOME NOME_CIRCUITO,
    C.LOCAL,
    C.CARACTERISTICAS,
    R.POSICAO_LARGADA,
    R.PONTOS_GANHOS,
    R.POSICAO_CHEGADA,
    R.STATUS_FINAL,
    R.VOLTA_MAIS_RAPIDA
 FROM TB_PILOTOS P
 INNER JOIN TB_CONSTRUTORES E 
 ON P.ID_CONSTRUTOR = E.ID_CONSTRUTOR
 INNER JOIN TB_RESULTADOS R 
 ON R.ID_PILOTO = P.ID_PILOTO
 INNER JOIN TB_CIRCUITOS C
 ON C.ID_CIRCUITO = R.ID_CIRCUITO
 INNER JOIN TB_TEMPORADAS T
 ON T.ANO = R.ANO;

CREATE OR REPLACE PROCEDURE PRC_CARGA_DADOS_F1 AS
BEGIN
    -- [A] GARANTE OS CONSTRUTORES (EQUIPES)
    MERGE INTO TB_CONSTRUTORES E
    USING (SELECT DISTINCT STG_EQUIPE FROM STG_F1_CARGA WHERE STG_EQUIPE IS NOT NULL) S
    ON (E.EQUIPE = S.STG_EQUIPE)
    WHEN NOT MATCHED THEN
        INSERT (ID_CONSTRUTOR, EQUIPE)
        VALUES (SEQ_CONSTRUTOR.NEXTVAL, S.STG_EQUIPE);

    -- [B] GARANTE OS CIRCUITOS
    MERGE INTO TB_CIRCUITOS C
    USING (SELECT DISTINCT STG_CIRCUITO FROM STG_F1_CARGA WHERE STG_CIRCUITO IS NOT NULL) S
    ON (C.NOME = S.STG_CIRCUITO)
    WHEN NOT MATCHED THEN
        INSERT (ID_CIRCUITO, NOME)
        VALUES (SEQ_CIRCUITO.NEXTVAL, S.STG_CIRCUITO);

    -- [C] GARANTE OS PILOTOS (LIGANDO À EQUIPE)
    MERGE INTO TB_PILOTOS P
    USING (
        SELECT DISTINCT 
            S.STG_NOME_PILOTO, 
            S.STG_SIGLA_PILOTO, 
            E.ID_CONSTRUTOR
        FROM STG_F1_CARGA S
        JOIN TB_CONSTRUTORES E ON S.STG_EQUIPE = E.EQUIPE
        WHERE S.STG_NOME_PILOTO IS NOT NULL
    ) S
    ON (P.NOME = S.STG_NOME_PILOTO)
    WHEN NOT MATCHED THEN
        INSERT (ID_PILOTO, NOME, SIGLA, ID_CONSTRUTOR)
        VALUES (SEQ_PILOTO.NEXTVAL, S.STG_NOME_PILOTO, S.STG_SIGLA_PILOTO, S.ID_CONSTRUTOR);

    -- [D] ALIMENTA A TB_RESULTADOS (O CORAÇÃO DO DASHBOARD)
    INSERT INTO TB_RESULTADOS (
    ID_RESULTADO, ANO, ID_CIRCUITO, ID_PILOTO, 
    POSICAO_LARGADA, POSICAO_CHEGADA, PONTOS_GANHOS, 
    VOLTA_MAIS_RAPIDA, STATUS_FINAL
)
SELECT 
    SEQ_RESULTADO.NEXTVAL,
    TO_NUMBER(S.STG_ANO),
    C.ID_CIRCUITO,
    P.ID_PILOTO,
    TO_NUMBER(NVL(S.STG_POS_LARGADA, '0')),
    TO_NUMBER(NVL(S.STG_POS_CHEGADA, '0')),
    TO_NUMBER(NVL(S.STG_PONTOS, '0')),
    S.STG_VOLTA_RAPIDA,
    S.STG_STATUS_FINAL
FROM STG_F1_CARGA S
JOIN TB_PILOTOS P ON S.STG_NOME_PILOTO = P.NOME
JOIN TB_CIRCUITOS C ON S.STG_CIRCUITO = C.NOME
WHERE NOT EXISTS (
    SELECT 1 FROM TB_RESULTADOS R 
    WHERE R.ID_PILOTO = P.ID_PILOTO 
      AND R.ANO = TO_NUMBER(S.STG_ANO) 
      AND R.ID_CIRCUITO = C.ID_CIRCUITO
    );

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Carga concluída: Equipes, Circuitos, Pilotos e Resultados atualizados.');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERRO NA CARGA: ' || SQLERRM);
END;

CREATE SEQUENCE SEQ_CONSTRUTOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PILOTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CIRCUITO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESULTADO START WITH 1 INCREMENT BY 1;
